name: 📦 Repository
description: Git checkout
author: Ministry of Justice UK

# This action performs a Git checkout of the repository, retrieving the source code for
# subsequent analysis steps. It serves as the foundational step for all SCA operations,
# ensuring the latest code is available for scanning and review.

inputs:
  token:
    required: true
    description: "GitHub repository token with read and write permissions for contents, pull requests, and issues, plus read-only access to security events."

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
