name: Ministry of Justice UK - GitHub - Commit check 🔎
description: Validate whether the commit is signed and commit message is constructed in conventional commit format
author: Ministry of Justice UK

inputs:
  config-file:
    required: false
    description: "Commitlint configuration file, supplied to --config argument."

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: ministryofjustice/devsecops-actions/sca/repository@9babea875cafae0e3b05a5ec5aca76d6b560c42e

    - name: 🧩 Conventional
      shell: bash
      working-directory: ${{ github.workspace }}
      run: git log -1 --no-show-signature --pretty=%B | npx commitlint \
        --color  \
        --strict ${{ inputs.config-file && format('--config "{0}"', inputs.config-file) || 'commitlint.config.js' }}
