name: ✏️ Create
description: Validates whether the template repository has bee updated or not and then creates a new pull request if an update is available
author: Ministry of Justice UK

inputs:
  base-branch:
    required: false
    default: "main"
    description: "Base repository branch"

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: Update
      shell: bash
      run: cruft update --skip-apply-ask --strict

    - name: Variables
      shell: bash
      run: |
        BASE="${{ inputs.base-branch }}"
        BRANCH=chore/cookie-cutter-update-$(date +%Y%m%d)

        echo "BASE=$BASE" >> "$GITHUB_ENV"
        echo "BRANCH=$BRANCH" >> "$GITHUB_ENV"

    - name: Configure
      shell: bash
      run: |
        git config user.name "Ministry of Justice"
        git config user.email "github@justice.gov.uk"

    - name: Branch
      shell: bash
      run: git switch -c $BRANCH

    - name: Sign
      shell: bash
      run: |
        git config gpg.format ssh
        git config user.signingkey ~/.ssh/cruft
        git config commit.gpgsign true

    - name: Commit
      shell: bash
      run: |
        git add .
        git commit -S -m "chore(update): cruft update"

    - name: Push
      shell: bash
      run: |
        git remote -v
        git remote set-url origin https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git
        git push origin "$BRANCH"

    - name: PR
      shell: bash
      run: |
        curl -sSf \
        "https://api.github.com/repos/${{ github.repository }}/pulls" \
        -X POST \
        -H "Authorization: Bearer ${{ inputs.token }}" \
        -H "Accept: application/vnd.github+json" \
        -d '{
          "title": "chore(update): cruft update",
          "base": "'"$BASE"'",
          "head": "'"$BRANCH"'"
        }'
