name: 🔎 Check
description: Checks for cruft update, if available then proceed if not then exit silently
author: Ministry of Justice UK

runs:
  using: composite
  steps:
    - name: Update
      shell: bash
      run: cruft update --skip-apply-ask --strict
