name: 🔑 Authenticate
description: Authenticate with GitHub using SSH
author: Ministry of Justice UK

inputs:
  ssh-key:
    required: true
    description: "GitHub repository ssh private key"

  github-known-hosts:
    required: true
    description: "GitHub's SSH key fingerprints, we recommend using Ed25519"

runs:
  using: composite
  steps:
    - name: Directory
      shell: bash
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Keys
      shell: bash
      run: |
        echo "${{ inputs.ssh-key }}" > ~/.ssh/cruft
        chmod 600 ~/.ssh/cruft

    - name: Hosts
      shell: bash
      run: |
        printf '%s\n' "${{ inputs.github-known-hosts }}" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Configuration
      shell: bash
      run: |
        cat << 'EOF' > ~/.ssh/config
        Host github.com
          HostName github.com
          User git
          IdentityFile ~/.ssh/cruft
          IdentitiesOnly yes
          StrictHostKeyChecking yes
          AddKeysToAgent no
        EOF

        chmod 600 ~/.ssh/config
