name: 🔑 Secrets
description: Secrets, credentials, tokens scan
author: Ministry of Justice UK

# This action scans the repository for exposed secrets, credentials, API tokens, and other
# sensitive information using the Ministry of Justice DevSecOps hooks tool. It helps prevent
# accidental exposure of confidential data in source code, configuration files, and commit history.

inputs:
  token:
    required: true
    description: "GitHub repository token with read and write permissions for contents, pull requests, and issues, plus read-only access to security events."

runs:
  using: composite
  steps:
    - name: Scan
      shell: bash
      run: docker run --rm
        \-e GIT_MODE=false
        \-v "$(pwd)":/src
        \ghcr.io/ministryofjustice/devsecops-hooks:v1.3.0 # https://github.com/ministryofjustice/devsecops-hooks
