# Software Composition Analysis (SCA) GitHub Action
#
# This composite action performs comprehensive software composition analysis including:
# - Dependency review to identify vulnerabilities in project dependencies
# - Automated dependency updates via Renovate bot
# - Security scanning of dependencies
#
# Usage:
#   - uses: ministryofjustice/devsecops-actions/sca@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       renovate: 'true'
#       renovate-version: '42.64.1'
#       dependency-review-config-file: '.github/dependency-review-config.yml'
#
# Inputs:
#   renovate:
#     description: Enable or disable Renovate bot execution
#     required: false
#     default: 'true'
#
#   renovate-version:
#     description: Specific version of Renovate CLI to use
#     required: false
#     default: '42.64.1'
#
#   dependency-review-config-file:
#     description: Path to custom dependency review configuration file
#     required: false
#     default: ''
#
#   token:
#     description: GitHub token with required permissions (contents: read/write, pull-requests: read/write, issues: read/write, security-events: read)
#     required: true
#
# Steps:
#   1. Checks out the repository code
#   2. Runs dependency review action to scan for vulnerabilities
#   3. Executes Renovate bot (if enabled) to create automated dependency update PRs
#
# Requirements:
#   - GitHub token with appropriate permissions
#   - Repository must have dependency manifest files (package.json, requirements.txt, etc.)
#

name: Ministry of Justice UK - SCA ⚡️
description: Software composition analysis GitHub action focuses on dependencies, secret scanning and vulnerabilities management
author: Ministry of Justice UK

inputs:
  renovate:
    required: false
    description: "Flag to evaluation Renovate execution"
    default: "true"

  renovate-version:
    required: false
    description: "Renovate CLI version, an optional argument which defaults to v42.64.1."
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "GitHub Actions dependency review configuration file path relative to your repository."
    default: ""

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # frozen: v6.0.1

    - name: Dependencies
      uses: actions/dependency-review-action@774d14bf50b7a2e2460f9f49e25c52503ecab125 # frozen: v4.8.3
      with:
        config-file: ${{ inputs.dependency-review-config-file }}

    - name: Renovate
      if: inputs.renovate == 'true'
      uses: renovatebot/github-action@f7fad228a053c69a98e24f8e4f6cf40db8f61e08 # frozen: v44.2.1
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}
      env:
        RENOVATE_AUTODISCOVER: "false"
        RENOVATE_REPOSITORIES: ${{ github.repository }}
