name: Ministry of Justice UK - SCA ⚡️
description: Software composition analysis GitHub action for dependency management, secret scanning, and security vulnerability detection
author: Ministry of Justice UK

inputs:
  renovate:
    required: false
    description: "Flag to evaluation Renovate execution"
    default: "true"

  node_version:
    required: false
    description: "Node.js version to use"
    default: "24.11.1"

  renovate-version:
    required: false
    description: "Renovate CLI version, an optional argument which defaults to v42.64.1."
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "GitHub Actions dependency review configuration file path."
    default: ""

  trufflehog-config-file:
    required: false
    description: "Trufflehog configuration file path."
    default: ""

  codeql-config-file:
    required: false
    description: "CodeQL configuration file path."
    default: ""

  codeql-upload-findings:
    required: false
    description: "Upload the findings from CodeQL as SARIF file to Code Scanning, set to never if default setup is enabled."
    default: "always"

  docker-images-file:
    required: false
    description: "A JSON file an 'images' property as an array containing URIs to docker image, for example 'ghcr.io/ministryofjustice/devsecops-hooks:latest'"
    default: ""

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: ./repository

    - name: 📊 Dependencies
      uses: ./dependencies
      with:
        dependency-review-config-file: ${{ inputs.dependency-review-config-file }}

    - name: 🔎 OWASP
      uses: ./owasp

    - name: 🔁 Renovate
      if: ${{ inputs.renovate == 'true' }}
      uses: ./renovate
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}

    - name: 🔑 Secrets
      uses: ./secrets

    - name: 🐷 Trufflehog
      uses: ./trufflehog
      with:
        trufflehog-config-file: ${{ inputs.trufflehog-config-file }}

    - name: ⚙️ CodeQL
      uses: ./codeql
      with:
        codeql-config-file: ${{ inputs.codeql-config-file }}
        codeql-upload-findings: ${{ inputs.codeql-upload-findings }}

    - name: 🛡 OpenSSF
      uses: ./ossf
      with:
        token: ${{ inputs.token }}

    - name: 📋 SBOM
      uses: ./sbom
      with:
        token: ${{ inputs.token }}
        node_version: ${{ inputs.node_version }}
        docker-images-file: ${{ inputs.docker-images-file }}
