name: 🛡 OSSF
description: OSSF scan
author: Ministry of Justice UK

# This action runs the OpenSSF Scorecard tool to assess the security posture of the repository
# against industry best practises. It evaluates various security criteria including vulnerability
# management, code review practises, and security policies to provide a comprehensive security score.

inputs:
  token:
    required: true
    description: "GitHub repository token with read and write permissions for contents, pull requests, and issues, plus read-only access to security events."

runs:
  using: composite
  steps:
    - name: Install
      shell: bash
      run: |
        curl -L https://github.com/ossf/scorecard/releases/download/v5.4.0/scorecard_5.4.0_linux_amd64.tar.gz | tar -xz
        mv scorecard /usr/local/bin/scorecard
        chmod +x /usr/local/bin/scorecard

    - name: Scan
      shell: bash
      run: scorecard --local=./ --show-details --show-annotations --format json --output=sca-scorecard.json

    - name: Display
      shell: bash
      run: |
        echo "## 🛡 OSSF " >> $GITHUB_STEP_SUMMARY
        echo "### Score" >> $GITHUB_STEP_SUMMARY
        echo "**$(jq '.score' sca-scorecard.json)** / 10" >> $GITHUB_STEP_SUMMARY
        echo "### Overview" >> $GITHUB_STEP_SUMMARY
        echo "|Scan|Score (/10)|" >> $GITHUB_STEP_SUMMARY
        echo "|-----------|-----------|" >> $GITHUB_STEP_SUMMARY
        jq -r '.checks[] | "| \(.name) | \(.score) |"' sca-scorecard.json >> $GITHUB_STEP_SUMMARY
        echo "---" >> $GITHUB_STEP_SUMMARY
