name: Ministry of Justice UK - Cruft update 🚀
description: Cruft auto update pull request creation GitHub action
author: Ministry of Justice UK

inputs:
  python-version:
    required: false
    description: "Python version to use"
    default: 3.14.2

  private:
    required: false
    description: "Cruft template repository is private or not?"
    default: "false"

  ssh-key:
    required: false
    default: ""
    description: "GitHub repository ssh private key for private template repository access"

  github-known-hosts:
    required: false
    default: ""
    description: "GitHub's SSH key fingerprints, we recommend using Ed25519"

  base-branch:
    required: false
    default: "main"
    description: "Base repository branch"

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: ministryofjustice/devsecops-actions/sca/repository@9babea875cafae0e3b05a5ec5aca76d6b560c42e
      with:
        token: ${{ inputs.token }}

    - name: ⚒️ Install
      uses: ministryofjustice/devsecops-actions/cruft/install@feat/92-cruft-update---reusable-action
      with:
        python-version: ${{ inputs.python-version }}

    - name: 🔑 Authenticate
      if: ${{ inputs.private }} == 'true'
      uses: ministryofjustice/devsecops-actions/cruft/authenticate@feat/92-cruft-update---reusable-action
      with:
        ssh-key: ${{ inputs.ssh-key }}
        github-known-hosts: ${{ inputs.github-known-hosts }}

    - name: ✏️ Create
      uses: ministryofjustice/devsecops-actions/cruft/create@feat/92-cruft-update---reusable-action
      with:
        token: ${{ inputs.token }}
